@startuml C4_Elements

title "Arquitetura (C4)"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml

!include <office/Servers/file_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/application_web>
!include <office/Services/network_file_share_service>

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist

!include AzurePuml/AzureCommon.puml
!include AzurePuml/Storage/AzureBlobStorage.puml
!include AzurePuml/Integration/AzureServiceBus.puml

AddContainerTag("files", $sprite="file_server", $legendText="File Server")
AddContainerTag("webApp", $sprite="application_server", $legendText="WEB App")
AddContainerTag("bot", $sprite="service_application", $legendText="Worker Bot")
AddContainerTag("service", $sprite="network_file_share_service", $legendText="Worker")
AddContainerTag("api",$sprite="application_web",$legendText="WEB API")

AddElementTag("cobol",$bgColor="#000044",$legendText="COBOL")
AddElementTag("our",$bgColor="#008800",$legendText="Our implementations")

System_Boundary(aix, "AIX"){
    Container(erp, "ERP", "COBOL", $tags="cobol+webApp")
    Container(bot, "BOTs", "COBOL", $tags="cobol+bot")
    ContainerDb(fs, "File System", "SAMBA", $tags="files")
    Container(provider, "File Provider","Python",$tags="our+service")
}

Rel(bot,erp,"Get entity events")
Rel(bot,fs,"Writes to files")
Rel(provider,fs,"Reads files")

AddContainerTag("blob",$sprite="AzureBlobStorage",$legendText="Azure Blob Storage")
AddContainerTag("queue",$sprite="AzureServiceBus",$legendText="Azure Service Bus")

System_Boundary(cloud,"Azure Kubernetes System"){

    Container(rcv1, "File Receiver 1","C#",$tags="our+api")
    Container(rcv2, "File Receiver 2","C#",$tags="our+api")
    ContainerDb(blob, "Blob Storage",$tags="blob")
    ContainerDb(queue,"Service Bus Queue",$tags="queue")
}

Rel_R(provider,rcv1,"Send event file")
Rel_R(provider,rcv2,"Send event file")

Rel(rcv1,queue,"Publish message to queue")
Rel(rcv2,blob,"Publish file to blob")

SHOW_LEGEND()
@enduml