@startuml arquitetura-provider-flow-stop-control

!theme crt-amber

start

group Stop Control

    :load configuration;

    split
        if (is in execution\ntime window?) then (yes)
        else (no)
            end            
        endif
    split again
        if (is system in\nbackup mode?) then (yes)
            end
        else (no)            
        endif
    split again
        if (stop file\nexists?) then (yes)
            end
        else (no)           
        endif 
    end split
    

    

end group

:keep running;
stop
@enduml